const mongoose = require('mongoose');

const SalesSchema = new mongoose.Schema(
  {
    fileId: { type: mongoose.Schema.Types.ObjectId },
    channelId: { type: Number },
    chainName: { type: String, enum: ['RETAIL', 'DISTRIBUTION'] },
    store: { type: Number },
    storeName: { type: String },
    storeName3: { type: String },
    businessDate: { type: Date },
    tranSeqNo: { type: String },
    sdsOrdKposInvNo: { type: String },
    customerId: { type: String },
    customerName: { type: String },
    custBranchId: { type: String },
    branchName: { type: String },
    vanCustomerCode: { type: String },
    vanCustomerName: { type: String },
    salespersonId: { type: String },
    salespersonName: { type: String },
    division: { type: Number },
    divisionName: { type: String },
    brandId: { type: String },
    brandName: { type: String },
    dept: { type: String },
    deptName: { type: String },
    class: { type: String },
    className: { type: String },
    subclass: { type: String },
    subName: { type: String },
    item: { type: String },
    barcode: { type: String },
    itemDesc: { type: String },
    tranType: { type: String },
    qty: { type: Number },
    unitRetail: { type: Number },
    resaValue: { type: Number },
    legacyDepartment: { type: String },
    peDivision: { type: String },
    locationCode: { type: String },
  },
  { timestamps: true },
);

module.exports = mongoose.model('Sales', SalesSchema);
