const SECTOR_ENUM = {
  RETAIL_FASHION_AND_HOME: 'RETAIL_FASHION_AND_HOME',
  DISTRIBUTION_HOME: 'DISTRIBUTION_HOME',
  DISTRIBUTION_FMCG: 'DISTRIBUTION_FMCG',
  RETAIL_PERFUMERY: 'RETAIL_PERFUMERY',
  RETAIL_PHOTOGRAPHY: 'RETAIL_PHOTOGRAPHY',
  DISTRIBUTION_PHOTOGRAPHY: 'DISTRIBUTION_PHOTOGRAPHY',
  DISTRIBUTION_RETAIL_PHOTOGRAPHY: 'DISTRIBUTION_RETAIL_PHOTOGRAPHY',
  DISTRIBUTION_PERFUMERY: 'DISTRIBUTION_PERFUMERY',
};

const CHAIN_NAME_ENUM = { RETAIL: 'RETAIL', DISTRIBUTION: 'DISTRIBUTION' };

DIST_PHOTOGRAPHY_LOCATION_BUDGETS = {
  CQS: 'Carrefour',
  LHS: 'lulu',
  LMS: 'Lagoona mall',
  PMS: 'Plaza Studio',
};

const DP_POSITIONS = {
  TEAM_A: 'TEAM_A',
  TEAM_B: 'TEAM_B',
  TEAM_B2: 'TEAM_B2',
  TEAM_C: 'TEAM_C',
  TECH_SUPPORT: 'TECH_SUPPORT',
  MERCHANDISER: 'MERCHANDISER',
  INSTITUTIONAL: 'INSTITUTIONAL',
  VAN_SALES: 'VAN_SALES',
  MANAGER_CANON: 'MANAGER_CANON',
  BACK_OFFICE_CANON: 'BACK_OFFICE_CANON',
  MANAGER_ENERGIZER: 'MANAGER_ENERGIZER',
  BACK_OFFICE_ENERGIZER: 'BACK_OFFICE_ENERGIZER',
};

const FMCG_POSITIONS = {
  SALES_REPRESENTATIVE: 'SALES_REPRESENTATIVE',
  VAN_SALES: 'VAN_SALES',
  MANAGER: 'MANAGER',
  SUPERVISOR: 'SUPERVISOR',
  MERCHANDISER: 'MERCHANDISER',
  BACK_OFFICE: 'BACK_OFFICE',
};

const FASHION_AND_HOME_POSITIONS = {
  TAILOR_SUPERVISOR: 'TailorSupervisor',
  TAILOR: 'Tailor',
  CASHIER_SUPERVISOR: 'CashierSupervisor',
  CASHIER: 'Cashier',
  SERVICE_STAFF: 'ServiceStaff',
  STORE_KEEPER: 'Storekeeper',
};
const DIST_HOME = {
  BACK_OFFICE: 'BACK_OFFICE',
  MERCHANDISER: 'MERCHANDISER',
  MANAGER_SUPERVISOR_LUGGAGE: 'MANAGER_SUPERVISOR_LUGGAGE',
  MANAGER_SUPERVISOR_HOUSEHOLD: 'MANAGER_SUPERVISOR_HOUSEHOLD',
  MANAGER_SUPERVISOR_INSTITUTIONAL: 'MANAGER_SUPERVISOR_INSTITUTIONAL',
  SALES_REPRESENTATIVE: 'SALES_REPRESENTATIVE',
};
const RETAIL_PERFUMERY_POSITIONS = {
  BACK_OFFICE: 'BACK_OFFICE',
  STORE_MANAGER: 'STORE_MANAGER',
  STORE_SUPERVISOR: 'STORE_SUPERVISOR',
  CASHIER: 'CASHIER',
  RETAIL_GENERAL_FRAGRANCE: 'RETAIL_GENERAL_FRAGRANCE',
};

const DIST_PERFUMERY_POSITIONS = {
  BEAUTY_ADVISOR:"BEAUTY_ADVISOR",
  FRAGRANCE_ADVISOR:"FRAGRANCE_ADVISOR",
  FREELANCE_PROMOTER:"FREELANCE_PROMOTER",
  BEAUTY_ADVISOR_GUERLAIN:"BEAUTY_ADVISOR_GUERLAIN",
  MAKE_UP_EXPERT:"MAKE_UP_EXPERT",
  SKINCARE_EXPERT:"SKINCARE_EXPERT",
  FRAGRANCE_EXPERT:"FRAGRANCE_EXPERT",
  SALES_AND_MARKETING_SUPERVISOR:"SALES_AND_MARKETING_SUPERVISOR",
  BRAND_MANAGER:"BRAND_MANAGER",
  BACK_OFFICE: 'BACK_OFFICE',
  FREELANCE:"FREELANCE",
};

// const DIST_PERFUMERY_AND_BEAUTY = {
//   BEAUTY_ADVISOR:"BEAUTY_ADVISOR",
//   BEAUTY_ADVISOR_GUERLAIN:"BEAUTY_ADVISOR_GUERLAIN",
//   FRAGRANCE_ADVISOR:"FRAGRANCE_ADVISOR",
//   FREELANCE_PROMOTER:"FREELANCE_PROMOTER",
//   MAKE_UP_EXPERT:"MAKE_UP_EXPERT",
//   SKINCARE_EXPERT:"SKINCARE_EXPERT",
//   FRAGRANCE_EXPERT:"FRAGRANCE_EXPERT",
//   BACK_OFFICE: 'BACK_OFFICE',
// };

const TOP_NOTES_STORES = ['PE-LHT'];

module.exports = {
  SECTOR_ENUM,
  CHAIN_NAME_ENUM,
  DIST_PHOTOGRAPHY_LOCATION_BUDGETS,
  DP_POSITIONS,
  FMCG_POSITIONS,
  FASHION_AND_HOME_POSITIONS,
  DIST_HOME,
  RETAIL_PERFUMERY_POSITIONS,
  DIST_PERFUMERY_POSITIONS,
  TOP_NOTES_STORES,
};
